sudo: required

# dist: trusty

language: cpp

compiler:
  - gcc
#  - clang

os:
  - linux
#  - osx

services:
  - mysql

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gettext mariadb geoip lua libgcrypt pcre; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libmysqlclient-dev libpcre++-dev libgeoip-dev libssl-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install python2.7-dev liblua5.2-dev libperl-dev python-mysqldb; fi
  - mysql -u root -e "create database if not exists vh_test_xx; grant all on vh_test_xx.* to vh_test_xx@'127.0.0.1' identified by 'vh_test_xx'; flush privileges;"

before_script:
  - mkdir build
  - cd build
  - cmake -DDEFINE_DEBUG=ON -DINSTALL_CMAKE_FILES=OFF ..

script:
  - make
  - sudo make install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then vh_run_integration_test vh_test_xx vh_test_xx vh_test_xx; fi

